-- Phantom_Arsenal_localization
local mod = get_mod("Phantom_Arsenal")

return {
	mod_name = {
		en = "Phantom Arsenal",
		ru = "Фантомный арсенал",
		fr = "Arsenal fantôme",
		["zh-tw"] = "幻影武器庫",
		["zh-cn"] = "幻影武器库",
		de = "Phantom-Arsenal",
		it = "Arsenale Fantasma",
		ja = "ファントムアーセナル",
		ko = "팬텀 아스널",
		pl = "Arsenał Widmowy",
		["pt-br"] = "Arsenal Fantasma",
		es = "Arsenal Fantasmal",
	},
	mod_description = {
		en = "Adjust visibility of primary, secondary, grenade and special items independently with optional conditions.",
		ru = "Phantom Arsenal - Независимая настройка видимости основного и дополнительного оружия, а также гранат и специальных предметов с опциональными условиями.",
		fr = "Ajustez indépendamment la visibilité de vos armes principales, secondaires, grenades et objets spéciaux avec des conditions optionnelles.",
		["zh-tw"] = "獨立調整主要、次要、手榴彈和特殊物品的可見度，可選條件觸發。",
		["zh-cn"] = "独立调整主武器、副武器、手榴弹和特殊物品的可见度，可选条件触发。",
		de = "Passen Sie die Sichtbarkeit von Primär-, Sekundär-, Granaten- und Spezialwaffen unabhängig voneinander an, mit optionalen Bedingungen.",
		it = "Regola indipendentemente la visibilità di armi primarie, secondarie, granate e oggetti speciali con condizioni opzionali.",
		ja = "主要武器、副次武器、グレネード、特殊アイテムの透明度を個別に調整し、オプションの条件で切り替えられます。",
		ko = "주 무기, 보조 무기, 수류탄 및 특수 아이템의 가시성을 개별적으로 조정하며, 조건부 투명화를 설정할 수 있습니다.",
		pl = "Niezależnie dostosuj widoczność broni głównej, dodatkowej, granatów i przedmiotów specjalnych z opcjonalnymi warunkami.",
		["pt-br"] = "Ajuste independentemente a visibilidade de armas primárias, secundárias, granadas e itens especiais com condições opcionais.",
		es = "Ajusta independientemente la visibilidad de armas principales, secundarias, granadas y objetos especiales con condiciones opcionales.",
	},
	fade_speed = {
		en = "Fade Speed",
		ru = "Скорость затухания",
		fr = "Vitesse de fondu",
		["zh-tw"] = "淡出速度",
		["zh-cn"] = "淡出速度",
		de = "Überblendgeschwindigkeit",
		it = "Velocità dissolvenza",
		ja = "フェード速度",
		ko = "페이드 속도",
		pl = "Szybkość zanikania",
		["pt-br"] = "Velocidade de transição",
		es = "Velocidad de desvanecimiento",
	},
	mode_slot_primary = {
		en = Localize("loc_inventory_loadout_group_primary_weapon"),
	},
	opacity_slot_primary = {
		en = "Primary Weapon Visibility (%%)",
		ru = "Видимость основного оружия (%%)",
		fr = "Visibilité de l'arme principale (%%)",
		["zh-tw"] = "主要武器可見度 (%%)",
		["zh-cn"] = "主武器可见度 (%%)",
		de = "Sichtbarkeit Primärwaffe (%%)",
		it = "Visibilità arma primaria (%%)",
		ja = "主要武器の可視性 (%%)",
		ko = "주 무기 가시성 (%%)",
		pl = "Widoczność broni głównej (%%)",
		["pt-br"] = "Visibilidade da arma primária (%%)",
		es = "Visibilidad de arma principal (%%)",
	},
	mode_slot_secondary = {
		en = Localize("loc_inventory_loadout_group_secondary_weapon"),
	},
	opacity_slot_secondary = {
		en = "Secondary Weapon Visibility (%%)",
		ru = "Видимость дополнительного оружия (%%)",
		fr = "Visibilité de l'arme secondaire (%%)",
		["zh-tw"] = "次要武器可見度 (%%)",
		["zh-cn"] = "副武器可见度 (%%)",
		de = "Sichtbarkeit Sekundärwaffe (%%)",
		it = "Visibilità arma secondaria (%%)",
		ja = "副次武器の可視性 (%%)",
		ko = "보조 무기 가시성 (%%)",
		pl = "Widoczność broni dodatkowej (%%)",
		["pt-br"] = "Visibilidade da arma secundária (%%)",
		es = "Visibilidad de arma secundaria (%%)",
	},
	mode_slot_grenade = {
		en = "Grenade Slot",
		ru = "Слот гранаты",
		fr = "Emplacement de grenade",
		["zh-tw"] = "手榴彈欄位",
		["zh-cn"] = "手榴弹栏位",
		de = "Granatenplatz",
		it = "Slot granata",
		ja = "グレネードスロット",
		ko = "수류탄 슬롯",
		pl = "Slot na granat",
		["pt-br"] = "Slot de granada",
		es = "Ranura de granada",
	},
	opacity_slot_grenade = {
		en = "Grenade Weapon Visibility (%%)",
		ru = "Видимость гранатного оружия (%%)",
		fr = "Visibilité de l'arme grenade (%%)",
		["zh-tw"] = "手榴彈武器可見度 (%%)",
		["zh-cn"] = "手榴弹武器可见度 (%%)",
		de = "Sichtbarkeit Granatenwaffe (%%)",
		it = "Visibilità arma granata (%%)",
		ja = "グレネード武器の可視性 (%%)",
		ko = "수류탄 무기 가시성 (%%)",
		pl = "Widoczność broni granatowej (%%)",
		["pt-br"] = "Visibilidade da arma de granada (%%)",
		es = "Visibilidad de arma de granada (%%)",
	},
	mode_slot_special = {
		en = "Special Items",
		ru = "Специальные предметы",
		fr = "Objets spéciaux",
		["zh-tw"] = "特殊物品",
		["zh-cn"] = "特殊物品",
		de = "Spezialgegenstände",
		it = "Oggetti speciali",
		ja = "特殊アイテム",
		ko = "특수 아이템",
		pl = "Przedmioty specjalne",
		["pt-br"] = "Itens especiais",
		es = "Objetos especiales",
	},
	opacity_slot_special = {
		en = "Special Items Visibility (%%)",
		ru = "Видимость спецпредметов (%%)",
		fr = "Visibilité objets spéciaux (%%)",
		["zh-tw"] = "特殊物品可見度 (%%)",
		["zh-cn"] = "特殊物品可见度 (%%)",
		de = "Sichtbarkeit Spezialgegenstände (%%)",
		it = "Visibilità oggetti speciali (%%)",
		ja = "特殊アイテムの可視性 (%%)",
		ko = "특수 아이템 가시성 (%%)",
		pl = "Widoczność przedmiotów specjalnych (%%)",
		["pt-br"] = "Visibilidade de itens especiais (%%)",
		es = "Visibilidad de objetos especiales (%%)",
	},
	setting_always = {
		en = "Always",
		ru = "Всегда",
		fr = "Toujours",
		["zh-tw"] = "總是",
		["zh-cn"] = "总是",
		de = "Immer",
		it = "Sempre",
		ja = "常に",
		ko = "항상",
		pl = "Zawsze",
		["pt-br"] = "Sempre",
		es = "Siempre",
	},
	setting_on_block_all = {
		en = "On Block (all melee)",
		ru = "При блоке (всё ближнее)",
		fr = "En blocage (tout)",
		de = "Beim Blocken (alle)",
		it = "In blocco (tutto)",
		es = "Al bloquear (todo)",
		pl = "Przy bloku (wszystko)",
	},
	setting_on_block_shields = {
		en = "On Block (shields only)",
		ru = "При блоке (только щиты)",
		fr = "En blocage (boucliers)",
		de = "Beim Blocken (Schilde)",
		it = "In blocco (scudi)",
		es = "Al bloquear (escudos)",
		pl = "Przy bloku (tylko tarcze)",
	},
	setting_on_block_no_shields = {
		en = "On Block (except shields)",
		ru = "При блоке (кроме щитов)",
		fr = "En blocage (sauf boucliers)",
		de = "Beim Blocken (außer Schilde)",
		it = "In blocco (tranne scudi)",
		es = "Al bloquear (excepto escudos)",
		pl = "Przy bloku (oprócz tarcz)",
	},
	setting_on_aim_all = {
		en = "On Aim (all ranged)",
		ru = "При прицеливании (всё дальнее)",
		fr = "En visée (tout)",
		de = "Beim Zielen (alle)",
		it = "In mira (tutto)",
		es = "Al apuntar (todo)",
		pl = "Przy celowaniu (wszystko)",
	},
	setting_on_aim_braced = {
		en = "On Aim (braced only)",
		ru = "При прицеливании (с упором)",
		fr = "En visée (avec appui)",
		de = "Beim Zielen (mit Stütze)",
		it = "In mira (con appoggio)",
		es = "Al apuntar (con apoyo)",
		pl = "Przy celowaniu (z podparciem)",
	},
	setting_on_aim_non_braced = {
		en = "On Aim (non-braced only)",
		ru = "При прицеливании (без упора)",
		fr = "En visée (sans appui)",
		de = "Beim Zielen (ohne Stütze)",
		it = "In mira (senza appoggio)",
		es = "Al apuntar (sin apoyo)",
		pl = "Przy celowaniu (bez podparcia)",
	},
	setting_on_aim_staves = {
		en = "On Aim (staves only)",
		ru = "При прицеливании (только посохи)",
		fr = "En visée (bâtons)",
		de = "Beim Zielen (Stäbe)",
		it = "In mira (bastoni)",
		es = "Al apuntar (báculos)",
		pl = "Przy celowaniu (tylko kostury)",
	},
	setting_on_aim_except_staves = {
		en = "On Aim (except staves)",
		ru = "При прицеливании (кроме посохов)",
		fr = "En visée (sauf bâtons)",
		de = "Beim Zielen (außer Stäbe)",
		it = "In mira (tranne bastoni)",
		es = "Al apuntar (excepto báculos)",
		pl = "Przy celowaniu (oprócz kosturów)",
	},
	setting_never = {
		en = "Never",
		ru = "Никогда",
		fr = "Jamais",
		["zh-tw"] = "永不",
		["zh-cn"] = "永不",
		de = "Nie",
		it = "Mai",
		ja = "なし",
		ko = "안 함",
		pl = "Nigdy",
		["pt-br"] = "Nunca",
		es = "Nunca",
	},
}
